import Testing

struct InventoryListManagementLocalizationTests {
    @Test func actionAndTitleLabelsFollowLocaleConventions() {
        #expect(localizationTestValue("inventory.action.edit", language: "en") == "Edit")
        #expect(localizationTestValue("inventory.action.rename", language: "en") == "Rename")
        #expect(localizationTestValue("inventory.action.editItem", language: "en") == "Edit Item")
        #expect(localizationTestValue("inventory.lists.editLocation", language: "en") == "Edit Location")
        #expect(localizationTestValue("inventory.lists.renameCategory", language: "en") == "Rename Category")
        #expect(localizationTestValue("settings.lists.locations.accessibilityLabel", language: "en") == "Manage Locations")
        #expect(localizationTestValue("settings.lists.places.accessibilityLabel", language: "en") == "Manage Storage Places")
        #expect(localizationTestValue("settings.lists.categories.accessibilityLabel", language: "en") == "Manage Categories")
        #expect(localizationTestValue("inventory.action.addItem.accessibilityLabel", language: "en") == "Add Item")
        #expect(localizationTestValue("settings.backup.accessibilityLabel", language: "en") == "Back Up Inventory")
        #expect(localizationTestValue("settings.restore.accessibilityLabel", language: "en") == "Restore Inventory from Backup")
        #expect(localizationTestValue("settings.export.accessibilityLabel", language: "en") == "Export Inventory")
        #expect(localizationTestValue("inventory.lists.error.placeDoesNotBelongToLocation.message", language: "en") == "This storage place does not belong to the selected location.")

        #expect(localizationTestValue("inventory.action.edit") == "Редагувати")
        #expect(localizationTestValue("inventory.action.rename") == "Перейменувати")
        #expect(localizationTestValue("inventory.action.editItem") == "Редагувати річ")
        #expect(localizationTestValue("inventory.lists.editLocation") == "Редагувати локацію")
        #expect(localizationTestValue("inventory.lists.renameCategory") == "Перейменувати категорію")
    }

    @Test func ukrainianListManagementStringsResolveFromCatalog() {
        #expect(localizationTestValue("inventory.lists.title") == "Керування списками")
        #expect(localizationTestValue("inventory.lists.locations") == "Локації")
        #expect(localizationTestValue("inventory.lists.locations.title") == "Керування локаціями")
        #expect(localizationTestValue("inventory.lists.categories") == "Категорії")
        #expect(localizationTestValue("inventory.lists.categories.title") == "Керування категоріями")
        #expect(localizationTestValue("inventory.lists.locations.empty") == "Багаторазових локацій ще немає.")
        #expect(localizationTestValue("inventory.lists.addLocation") == "Додати локацію")
        #expect(localizationTestValue("inventory.lists.addCategory") == "Додати категорію")
        #expect(localizationTestValue("inventory.lists.editLocation") == "Редагувати локацію")
        #expect(localizationTestValue("inventory.lists.renameCategory") == "Перейменувати категорію")
        #expect(localizationTestValue("inventory.action.edit") == "Редагувати")
        #expect(localizationTestValue("inventory.action.rename") == "Перейменувати")
        #expect(localizationTestValue("inventory.lists.defaultBadge") == "Типова")
        #expect(localizationTestValue("inventory.lists.actions") == "Дії зі значенням списку")
        #expect(localizationTestValue("inventory.lists.delete.title") == "Видалити значення?")
        #expect(localizationTestValue("inventory.lists.error.empty.title") == "Потрібна назва")
        #expect(localizationTestValue("inventory.lists.error.duplicate.title") == "Назва вже існує")
        #expect(localizationTestValue("inventory.lists.error.default.title") == "Типова категорія")
        #expect(localizationTestValue("inventory.lists.error.used.title") == "Значення використовується")
        #expect(localizationTestValue("inventory.lists.error.save.title") == "Список не оновлено")
        #expect(localizationTestValue("inventory.lists.error.save.message") == "Не вдалося зберегти зміни списку. Спробуйте ще раз.")
        #expect(localizationTestValue("inventory.lists.error.delete.title") == "Значення не видалено")
        #expect(localizationTestValue("inventory.lists.error.delete.validationMessage") == "Не вдалося перевірити значення перед видаленням. Спробуйте ще раз.")
        #expect(localizationTestValue("inventory.lists.error.delete.message") == "Не вдалося видалити значення. Спробуйте ще раз.")
        #expect(localizationTestValue("inventory.lists.viewItems") == "Переглянути речі")
        #expect(localizationTestValue("inventory.lists.viewItems.location.accessibilityLabel") == "Переглянути речі в «%@», %@")
        #expect(localizationTestValue("inventory.lists.viewItems.category.accessibilityLabel") == "Переглянути речі в категорії «%@», %@")
        #expect(localizationTestValue("inventory.lists.items.empty.title") == "Немає речей")
        #expect(localizationTestValue("inventory.selection.creation.error.title") == "Значення не збережено")
        #expect(localizationTestValue("inventory.selection.creation.error.message") == "Не вдалося зберегти це значення. Спробуйте ще раз.")
        #expect(localizationTestValue("settings.lists.places") == "Місця зберігання")
        #expect(localizationTestValue("settings.lists.places.accessibilityLabel") == "Керувати місцями зберігання")
        #expect(localizationTestValue("inventory.places.title") == "Місця зберігання")
        #expect(localizationTestValue("inventory.places.add") == "Додати місце зберігання")
        #expect(localizationTestValue("inventory.places.empty.noLocations.message") == "Місце зберігання — це точна полиця, шухляда, коробка або органайзер усередині локації.")
        #expect(localizationTestValue("inventory.places.location.help") == "Виберіть батьківську локацію для цього місця зберігання.")
        #expect(localizationTestValue("inventory.lists.error.locationContainsPlaces.message.one") == "«%@» містить %d місце зберігання. Видаліть це місце зберігання перед видаленням локації.")
        #expect(localizationTestValue("inventory.lists.error.locationContainsPlaces.message.few") == "«%@» містить %d місця зберігання. Видаліть ці місця зберігання перед видаленням локації.")
        #expect(localizationTestValue("inventory.lists.error.locationContainsPlaces.message.many") == "«%@» містить %d місць зберігання. Видаліть ці місця зберігання перед видаленням локації.")
        #expect(localizationTestValue("inventory.lists.error.placeDoesNotBelongToLocation.message") == "Це місце зберігання не належить вибраній локації.")
    }
}
